# Meta Data for SEO

## Homepage
title = "Hyas"
titleSeparator = "-"
titleAddition = "Bootstrap Starter"
description = "Build your next web project with the official Bootstrap starter for Hyas."

## Open Graph
images = ["hyas.png"]
ogLocale = "en_US"
titleHome = "Hyas Hugo Starter"

## Twitter Cards
twitterSite = "@gethyas"
twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Hyas"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/henkverlinde"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "en-US"
schemaLogo = "logo-hyas.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "hyas.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/gethyas"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/h-enk/hyas"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Footer
footer = "Powered by <a href=\"https://getbootstrap.com/\">Bootstrap</a> and <a href=\"https://gethyas.com/\">Hyas</a>"

# Images

## defaultImage
defaultImage = "default-image.jpg" # put in `./assets/images/`

## imaging
[imaging]
  anchor = 'Smart'
  bgColor = '#fff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'Lanczos'

## lazyimg
[lazyimg]
  resizer = "auto"
  renderer = "lqip-webp"

  # Resizer options:
  lqipSize = "120x Gaussian"
  # maxSize = "1920x"
  maxSize = "1366x"
  responsiveSizes = [ "320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x" ]
  resizeOptions = "Lanczos q95"

  # Renderer options:
  class = "img-fluid"
  # alt = ""
  noscript = true

  errorHandler = "warning"
